<?php

declare(strict_types=1);

namespace Token27\NexusAI\Agents\Planning;

/**
 * An execution plan generated by the planner.
 *
 * Contains the ordered list of steps, the overall goal, and the reasoning
 * behind why these steps were chosen.
 *
 * @see \Token27\NexusAI\Agents\Planning\PlanStep
 * @see \Token27\NexusAI\Agents\Contract\PlannerInterface
 */
final readonly class Plan
{
    /**
     * @param array<PlanStep> $steps Ordered list of execution steps.
     * @param string $goal The overall objective of the plan.
     * @param string $reasoning Why the planner chose these steps.
     */
    public function __construct(
        public array $steps,
        public string $goal = '',
        public string $reasoning = '',
    ) {
    }

    /**
     * Serializes the plan to an array for trace/debugging.
     *
     * @return array<string, mixed> The plan as an array.
     */
    public function toArray(): array
    {
        return [
            'steps' => array_map(static fn (PlanStep $step): array => $step->toArray(), $this->steps),
            'goal' => $this->goal,
            'reasoning' => $this->reasoning,
        ];
    }
}
